// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SamirBoulema.TSVN
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidImagesString = "1a3d6932-4781-4605-861f-47dbe78e262b";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string guidTSVNPkgString = "f2e68d5a-c95e-4d53-bbc6-072ff3ed9c53";
        public static Guid guidTSVNPkg = new Guid(guidTSVNPkgString);

        public const string guidTSVNCmdSetString = "65ab72da-3aa4-4e36-8182-b3dbe7ff6b56";
        public static Guid guidTSVNCmdSet = new Guid(guidTSVNCmdSetString);

        public const string guidWorkspaceExplorerToolWindowCmdSetString = "cfb400f1-5c60-4f3c-856e-180d28def0b7";
        public static Guid guidWorkspaceExplorerToolWindowCmdSet = new Guid(guidWorkspaceExplorerToolWindowCmdSetString);

        public const string HTMLContextString = "78f03954-2fb8-4087-8ce7-59d71710b3bb";
        public static Guid HTMLContext = new Guid(HTMLContextString);

        public const string CSSContextString = "64da400e-b4ad-4d67-aa92-4b7acb01ecd5";
        public static Guid CSSContext = new Guid(CSSContextString);

        public const string ASPXContextString = "d7e8c5e1-bdb8-11d0-9c88-0000f8040a53";
        public static Guid ASPXContext = new Guid(ASPXContextString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int showChanges = 0x0001;
        public const int pull = 0x0002;
        public const int push = 0x0003;
        public const int showLog = 0x0004;
        public const int revert = 0x0005;
        public const int branch = 0x0006;
        public const int merge = 0x0007;
        public const int differences = 0x0008;
        public const int blame = 0x0009;
        public const int repo = 0x000A;
        public const int resolve = 0x000B;
        public const int sync = 0x000C;
        public const int commit = 0x000D;
        public const int disk = 0x000E;
        public const int switchImage = 0x000F;
        public const int cleanup = 0x0010;
        public const int stash = 0x0011;
        public const int fetch = 0x0012;
        public const int add = 0x0013;
        public const int properties = 0x0014;
        public const int delete = 0x0015;
        public const int shelve = 0x0016;
        public const int lockImage = 0x0017;
        public const int unlock = 0x0018;
        public const int rename = 0x0019;
        public const int Toolbar = 0x1000;
        public const int ToolbarGroup = 0x1050;
        public const int TSVNMenu = 0x1021;
        public const int firstMenuGroup = 0x1020;
        public const int secondMenuGroup = 0x1022;
        public const int thirdMenuGroup = 0x1023;
        public const int fourthMenuGroup = 0x1024;
        public const int fifthMenuGroup = 0x1025;
        public const int sixthMenuGroup = 0x1040;
        public const int TSVNItemMenu = 0x1032;
        public const int itemMenuGroup = 0x1033;
        public const int firstItemMenuGroup = 0x1034;
        public const int secondItemMenuGroup = 0x1035;
        public const int thirdItemMenuGroup = 0x1036;
        public const int fourthItemMenuGroup = 0x1037;
        public const int TSVNContextMenu = 0x1027;
        public const int contextMenuGroup = 0x1026;
        public const int firstContextMenuGroup = 0x1028;
        public const int secondContextMenuGroup = 0x1029;
        public const int thirdContextMenuGroup = 0x1030;
        public const int fourthContextMenuGroup = 0x1031;
        public const int TSVNMainContextMenu = 0x1038;
        public const int contextMainMenuGroup = 0x1039;
        public const int showChangesCommand = 0x0100;
        public const int updateCommand = 0x0101;
        public const int commitCommand = 0x0102;
        public const int showLogCommand = 0x0200;
        public const int diskBrowserCommand = 0x0201;
        public const int repoBrowserCommand = 0x0202;
        public const int createPatchCommand = 0x0300;
        public const int applyPatchCommand = 0x0301;
        public const int shelveCommand = 0x0302;
        public const int unshelveCommand = 0x0303;
        public const int branchCommand = 0x0400;
        public const int switchCommand = 0x0401;
        public const int mergeCommand = 0x0402;
        public const int revertCommand = 0x0500;
        public const int updateToRevisionCommand = 0x0501;
        public const int cleanupCommand = 0x0502;
        public const int lockCommand = 0x0503;
        public const int unlockCommand = 0x0504;
        public const int showLogFileCommand = 0x0600;
        public const int blameCommand = 0x0601;
        public const int differencesCommand = 0x0602;
        public const int diskBrowserFileCommand = 0x0603;
        public const int repoBrowserFileCommand = 0x0604;
        public const int mergeFileCommand = 0x0605;
        public const int updateToRevisionFileCommand = 0x0606;
        public const int propertiesCommand = 0x0607;
        public const int updateFileCommand = 0x0608;
        public const int commitFileCommand = 0x0609;
        public const int diffPreviousCommand = 0x0610;
        public const int revertFileCommand = 0x0611;
        public const int addFileCommand = 0x0612;
        public const int deleteFileCommand = 0x0613;
        public const int lockFileCommand = 0x0615;
        public const int unlockFileCommand = 0x0616;
        public const int renameFileCommand = 0x0617;
        public const int showOptionsDialogCommand = 0x0614;
        public const int TSVNWindowMenu = 0x2000;
        public const int TSVNWindowMenuGroup = 0x2001;
        public const int showToolwindowCommand = 0x2002;
        public const int idmWSE_ContextMenu = 0x0002;
        public const int HTMLContextMenu = 0x0001;
        public const int CSSContextMenu = 0x0002;
        public const int ASPXContextMenu = 0x0035;
    }
}